trigger: none

pool: IT stocks

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
    backendAzureRmStorageAccountName: 'dhondhustorage'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'smartyvipul.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'
    outputTo: 'console'
    customCommand: 'fmt'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoappinfra'